import { ImageInformationI } from '../interfaces/image-information.interface';

export const allPhotos: ImageInformationI[] = [
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0010.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0013.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0014.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0015.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0020.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0022.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0023.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0024.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0025.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0026.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0027.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0028.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0029.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0030.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0031.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0032.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0033.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0034.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0035.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0036.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0037.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0038.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0039.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0040.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0041.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0042.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0043.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/102.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/105.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/107.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/108.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/109.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/111.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/112.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/113.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/114.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/115.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/116.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/117.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/118.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/119.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/120.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/121.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/122.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/123.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/124.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/125.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/126.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/127.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/128.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/129.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/130.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/131.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/132.jpg' },
  { important: false, alt: 'lluvia', title: 'lluvia', description: 'lluvia', src: 'assets/photos/gallery/133.jpg' },
  { important: false, alt: 'lluvia', title: 'lluvia', description: 'lluvia', src: 'assets/photos/gallery/134.jpg' },
  { important: false, alt: 'lluvia', title: 'lluvia', description: 'lluvia', src: 'assets/photos/gallery/135.jpg' },
  { important: false, alt: 'lluvia', title: 'lluvia', description: 'lluvia', src: 'assets/photos/gallery/136.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/137.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/138.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/139.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/140.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/141.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/142.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/143.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/144.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/145.jpg' },
  { important: false, alt: 'humedal', title: 'humedal', description: 'humedal', src: 'assets/photos/gallery/146.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/147.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/148.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/149.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/150.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/151.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/152.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/153.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/154.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/155.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/156.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/157.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/158.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/159.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/160.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/161.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/162.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/163.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/164.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/165.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/166.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/167.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/168.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/169.jpg' },
  { important: false, alt: 'paipa', title: 'paipa', description: 'paipa', src: 'assets/photos/gallery/170.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/171.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/172.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/173.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/174.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/175.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/176.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/177.jpg' },
  { important: false, alt: 'Cementera Pueblo Fantasma', title: 'Cementera Pueblo Fantasma', description: 'Cementera Pueblo Fantasma', src: 'assets/photos/gallery/178.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/179.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/180.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/181.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/182.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/183.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/184.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/185.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/186.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/187.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/188.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/189.jpg' },
  { important: false, alt: 'Farallones de Sutatausa', title: 'Farallones de Sutatausa', description: 'Farallones de Sutatausa', src: 'assets/photos/gallery/190.jpg' }
];
