import { ImageInformationI } from '../interfaces/image-information.interface';

export const allPhotos: ImageInformationI[] = [
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0001.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0002.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0003.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0004.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0005.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0006.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0007.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0008.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0009.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0010.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0011.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0012.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0013.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0014.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0015.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0016.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0017.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0018.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0019.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0020.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0021.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0022.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0023.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0024.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0025.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0026.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0027.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0028.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0029.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0030.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0031.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0032.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0033.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0034.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0035.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0036.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0037.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0038.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0039.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0040.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0041.jpg' },
  { important: true, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0042.jpg' },
  { important: false, alt: 'unnamed', title: 'unnamed', description: 'unnamed', src: 'assets/photos/gallery/0043.jpg' }
];
